Add more wallets & orders.
Marfusios/crypto-websocket-extensions pull request #5
Opened 2020-01-26 16:58 UTC by ColossusFX

You need to update coinbase pro websocket client to get the user data.
I have yet to port my code to your library, so I am using 2 different coinbase libraries right now.

This pull request is mainly for you to cherry pick.

I have ported this from my working library, but have yet to test it.

I will upload bitstamp library asap.

2020-02-14 08:11 UTC, Marfusios requested changes

2020-02-14 08:11 UTC, Marfusios commented on src/Crypto.Websocket.Extensions.Core/Wallets/CryptoWallets.cs
> +        public CryptoWalletCollectionReadonly GetWallets(string currency, string exchangeName)
`CryptoWallets` is already bound to one specific exchange, what is the purpose of the `exchangeName` parameter?

2020-02-14 08:11 UTC, Marfusios commented on src/Crypto.Websocket.Extensions/Crypto.Websocket.Extensions.csproj
> +      <HintPath>..\..\..\..\Crypto.Arbitrage\crypto-websocket-extensions\src\Crypto.Websocket.Extensions.Core\bin\Debug\netstandard2.0\Crypto.Websocket.Extensions.Core.dll</HintPath>
Could you remove these hints to the path on the local disk?

2020-02-14 08:11 UTC, Marfusios commented on src/Crypto.Websocket.Extensions.Core/Orders/CryptoOrders.cs
> +    ///     Orders manager
Please avoid changing the existing code as much as possible (also below with order switching).

2020-02-14 08:11 UTC, Marfusios commented on src/Crypto.Websocket.Extensions.Core/Orders/CryptoOrders.cs
> +            throw new NotImplementedException();
?

2020-02-14 08:11 UTC, Marfusios commented on src/Crypto.Websocket.Extensions.Core/Orders/CryptoOrders.cs
> +            foreach (var order in orders) OnOrderUpdated(order);
Please, don't leave curly brackets or at least put it on the new line

2020-02-14 08:36 UTC, ColossusFX commented
Apologies it was late.
I will should be able to finish and test this weekend.

2020-02-27 13:25 UTC, Marfusios commented
@ColossusFX ping when you will be ready

2020-02-27 13:45 UTC, ColossusFX commented
I have added authed rest requests in coinbase lib now.

Just need to finish testing / converting over the weekend.

2020-05-23 15:43 UTC, closed without merging